all: spawnA.v hijo1.v spawnB.v spawnC.v spawnD.v hijo2.v spawnF.v




hijo1.v: hijo1.c
	gcc -o hijo1.v hijo1.c

hijo2.v: hijo2.c
	gcc -o hijo2.v hijo2.c

spawnA.v: spawnA.c
	gcc -o spawnA.v spawnA.c
	
spawnB.v: spawnB.c
	gcc -o spawnB.v spawnB.c

spawnC.v: spawnC.c
	gcc -o spawnC.v spawnC.c

spawnD.v: spawnD.c
	gcc -o spawnD.v spawnD.c

spawnF.v: spawnF.c
	gcc -o spawnF.v spawnF.c


clean:
	rm -f *.v