all: alarma2 alarma3 loop

alarma2: ejemplo_alarm2.c
	gcc -o alarma2 ejemplo_alarm2.c

alarma3: ejemplo_alarm3.c
	gcc -o alarma3 ejemplo_alarm3.c

loop: loop.c
	gcc -o loop loop.c

clean:
	rm -rf alarma2 alarma3 loop